server:
  port: 8084
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/dan?useUnicode=true&characterEncoding=utf8
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
  application:
    name: user-service # 应用名称
  main:
    allow-bean-definition-overriding: true #当遇到同样名字的时候，是否允许覆盖注册
#    druid:
#      initial-size: 1
#      min-idle: 1
#      max-active: 20
#      test-on-borrow: true
#      stat-view-servlet:
#        allow: true
eureka:
  client:
    service-url: # EurekaServer地址
      defaultZone: http://127.0.0.1:1112/eureka,http://127.0.0.1:1111/eureka
  instance:
    prefer-ip-address: true #当调用getHostname获取实例的hostname时，返回ip而不是host
    ip-address: 127.0.0.1 #指定自己的ip信息，不指定的话会自己寻找
    lease-expiration-duration-in-seconds: 90 #90s得不到续约信息就默认为服务挂了
    lease-renewal-interval-in-seconds: 30  #每隔30s向服务发送一次续约
